Repository gnimty/backend-community-service, pull requests merged in 2023-12, with the labels that each got.

#86 Test/#85 ChatService 테스트및 리펙토링
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/MessageRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/UserService.java
  src/main/java/com/gnimty/communityapiserver/global/exception/ErrorCode.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/OldStompServiceTest.java
Labels: Refactor, Test

#88 Test/#87 ChatRoomService 테스트및 리펙토링
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/ChatRoom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatRoomService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/global/exception/ErrorCode.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatRoomServiceTest.java
Labels: Refactor, Test

#95 Fix/#78: riot account bulk insert 결과가 empty list인 경우 user service 호출 X
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/RiotAccountController.java
Labels: Fix

#97 Test/#89 stompService 테스트및 리펙토링
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/UserService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/MemberController.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/global/exception/ErrorCode.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatRoomServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/OldStompServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
Labels: Refactor, Test

#100 Fix/#98: user 필드 수정 (자유랭크 포함)
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/User.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/UserService.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/UserServiceTest.java
Labels: Refactor, Test

#103 Fix/#92 recent summoners
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/SummonerUpdateEntry.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/dto/response/RecentlySummonersResponse.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/entity/RiotAccount.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountJdbcRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountService.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/dto/response/RecentlySummonersServiceResponse.java
  src/test/java/com/gnimty/communityapiserver/service/member/MemberServiceTest.java
Labels: Fix

#105 bug: userService.save 컴파일 오류 해결
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/UserService.java
Labels: Bug

#108 Feat/#72 RSO 연동
  src/main/java/com/gnimty/communityapiserver/domain/member/service/MemberService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/utils/RiotOauthUtil.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/entity/RiotAccount.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/utils/RiotAccountUpdateUtil.java
  src/main/java/com/gnimty/communityapiserver/global/config/async/MailAsyncConfiguration.java
  src/main/java/com/gnimty/communityapiserver/global/config/async/RiotAccountAsyncConfiguration.java
Labels: Feature, Fix, Refactor

#109 Fix/#99 챔피언 운용법 수정사항
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/controller/dto/request/ChampionCommentsRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/controller/dto/request/ChampionCommentsUpdateRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/service/ChampionCommentsService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/service/dto/request/ChampionCommentsUpdateServiceRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/AuthService.java
  src/main/java/com/gnimty/communityapiserver/global/exception/ErrorCode.java
  src/main/java/com/gnimty/communityapiserver/global/validation/validator/ChildCommentsValidator.java
Labels: Fix

#111 Refactor/#106 literal형태 변수 상수로 대체
  src/main/java/com/gnimty/communityapiserver/domain/block/controller/dto/request/BlockRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/controller/dto/request/ChampionCommentsRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/controller/dto/request/ChampionCommentsUpdateRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/entity/ChampionComments.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/service/ChampionCommentsService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/service/dto/request/ChampionCommentsUpdateServiceRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/repository/ChampionCommentsLikeRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/introduction/service/IntroductionReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/MemberController.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/AuthService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/MemberService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/dto/response/IntroductionEntry.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/RiotAccountController.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountService.java
  src/main/java/com/gnimty/communityapiserver/domain/schedule/controller/dto/request/ScheduleEntry.java
  src/main/java/com/gnimty/communityapiserver/global/auth/JwtProvider.java
  src/main/java/com/gnimty/communityapiserver/global/constant/Auth.java
  src/main/java/com/gnimty/communityapiserver/global/constant/Bound.java
  src/main/java/com/gnimty/communityapiserver/global/constant/CommonStringType.java
  src/main/java/com/gnimty/communityapiserver/global/validation/validator/ChildCommentsValidator.java
  src/test/java/com/gnimty/communityapiserver/service/member/MemberServiceTest.java
Labels: Refactor

#114 Test/#101 채팅관련 테스트 추가및 오류 해결
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/User.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/UserServiceTest.java
Labels: Bug, Fix, Test

#116 Feat/#115 챔피언 운용법 report
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/controller/ChampionCommentsReportController.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/controller/dto/request/ChampionCommentsReportRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/entity/ChampionCommentsReport.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/reposiotry/ChampionCommentsReportQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/reposiotry/ChampionCommentsReportRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/service/ChampionCommentsReportService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/service/dto/request/ChampionCommentsReportServiceRequest.java
  src/main/java/com/gnimty/communityapiserver/global/constant/ReportType.java
  src/main/java/com/gnimty/communityapiserver/global/constant/ResponseMessage.java
  src/main/java/com/gnimty/communityapiserver/global/exception/ErrorCode.java
Labels: Feature
