Repository gnimty/backend-community-service, pull requests merged in 2023-11, with the labels that each got.

#34 Feat/#31 bugfix and get chat members
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
Labels: Feature, Fix

#37 feat/#36 구독자에게 message 보낼 때의 type으로 구분으로 변경, 접속상태 보낼 때 bug 수정
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/MessageResponse.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/main/java/com/gnimty/communityapiserver/global/constant/MessageType.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatServiceTest.java
Labels: Feature, Fix, Refactor

#39 Fix/#38 ChatService 의존 메서드 작성
  src/main/java/com/gnimty/communityapiserver/domain/block/controller/BlockController.java
  src/main/java/com/gnimty/communityapiserver/domain/block/service/BlockService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/MemberController.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/MemberService.java
Labels: Fix

#41 Test/#40 MemberController 테스트
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/MemberController.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/IntroductionUpdateRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/MyProfileUpdateRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/OauthLoginRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/PasswordEmailVerifyRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/PasswordUpdateRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/PreferGameModeUpdateRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/StatusUpdateRequest.java
  src/test/java/com/gnimty/communityapiserver/controller/ControllerTestSupport.java
  src/test/java/com/gnimty/communityapiserver/controller/member/MemberControllerTest.java
Labels: Fix, Test

#44 Feat/#43 repository func enhance
  src/main/java/com/gnimty/communityapiserver/domain/block/controller/BlockController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/Chat.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/ChatRoom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/User.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/Chat/ChatRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryCustom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryCustom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatRoomService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/SeqGeneratorService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/UserService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/MemberController.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
Labels: Chore, Refactor, Enhance

#47 Feat/#10 최근 플레이 한 소환사 추천 조회
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/RiotAccountController.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/dto/response/RecentlySummonersEntry.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/dto/response/RecentlySummonersResponse.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountService.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/dto/response/RecentlySummonersServiceResponse.java
Labels: Feature

#50 fix: ChatService to StompService
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/RiotAccountController.java
Labels: Bug

#45 feat/#42 채팅 읽는 로직 추가 및 MessageRequest 추가
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/MessageRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/MessageResponse.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/global/connect/WebSocketSessionManager.java
  src/main/java/com/gnimty/communityapiserver/global/constant/MessageRequestType.java
  src/main/java/com/gnimty/communityapiserver/global/constant/MessageResponseType.java
  src/main/java/com/gnimty/communityapiserver/global/constant/MessageType.java
  src/main/java/com/gnimty/communityapiserver/global/handler/StompHandler.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/UserRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
Labels: Feature

#60 Fix/#59 api endpoint 변경
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/UserService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/MemberController.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/MemberService.java
  src/main/java/com/gnimty/communityapiserver/global/config/WebConfiguration.java
  src/main/java/com/gnimty/communityapiserver/global/interceptor/MemberAuthInterceptor.java
  src/test/java/com/gnimty/communityapiserver/controller/ControllerTestSupport.java
  src/test/java/com/gnimty/communityapiserver/controller/member/MemberControllerTest.java
  src/test/java/com/gnimty/communityapiserver/service/member/MemberServiceTest.java
Labels: Fix, Refactor, Test

#67 REFACTOR/#65 tier 관련 상수 소문자로 변경
  src/main/java/com/gnimty/communityapiserver/domain/member/service/MemberService.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/global/constant/Tier.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/UserRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/member/MemberServiceTest.java
Labels: Refactor

#66 Fix/#58 비밀번호 재설정 관련 오류 수정
  src/main/java/com/gnimty/communityapiserver/domain/block/controller/BlockController.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/MemberService.java
  src/main/java/com/gnimty/communityapiserver/domain/memberlike/controller/MemberLikeController.java
  src/main/java/com/gnimty/communityapiserver/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnimty/communityapiserver/global/config/WebConfiguration.java
Labels: Bug, Fix

#71 Test/#69 AuthController 테스트
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/EmailAuthRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/EmailVerifyRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/LoginRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/SignupRequest.java
  src/test/java/com/gnimty/communityapiserver/controller/ControllerTestSupport.java
  src/test/java/com/gnimty/communityapiserver/controller/member/AuthControllerTest.java
Labels: Test

#56 fix: ChatRoomRepository and UserRepository Test debug
  src/test/java/com/gnimty/communityapiserver/controller/ControllerTestSupport.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/UserRepositoryTest.java
Labels: Bug

#76 Test/#75 차단 도메인 테스트
  src/main/java/com/gnimty/communityapiserver/domain/block/controller/BlockController.java
  src/main/java/com/gnimty/communityapiserver/domain/block/controller/dto/request/BlockClearRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/block/controller/dto/request/BlockRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/block/service/BlockReadService.java
  src/test/java/com/gnimty/communityapiserver/controller/ControllerTestSupport.java
  src/test/java/com/gnimty/communityapiserver/controller/block/BlockControllerTest.java
  src/test/java/com/gnimty/communityapiserver/service/block/BlockReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/block/BlockServiceTest.java
Labels: Test

#74 Test/#70 AuthService 테스트
  src/main/java/com/gnimty/communityapiserver/domain/member/service/AuthService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/MemberService.java
  src/main/java/com/gnimty/communityapiserver/global/auth/JwtProvider.java
  src/test/java/com/gnimty/communityapiserver/service/member/AuthServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/member/MemberServiceTest.java
Labels: Fix, Refactor, Test

#84 Refactor: stompService 메서드의 파라미터를 모두 엔티티로 변경
  src/main/java/com/gnimty/communityapiserver/domain/block/controller/BlockController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/MemberController.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/RiotAccountController.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
Labels: Refactor

#82 Feat: 사용자 탈퇴 시 관련 채팅 데이터 삭제
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/UserService.java
  src/main/java/com/gnimty/communityapiserver/global/constant/MessageResponseType.java
Labels: Feature

#73 Hotfix: jdbc query 오류 수정
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountJdbcRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountService.java
Labels: Bug, Fix

#80 Test/#72 User 테스트및 기능 수정
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/ChatDto.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/ChatRoomDto.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/UserDto.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/AutoIncrementSequence.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/Blocked.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/Chat.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/ChatRoom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/User.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/Chat/ChatRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryCustom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryCustom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatRoomService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/SeqGeneratorService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/UserService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/dto/UserWithBlockDto.java
  src/main/resources/application.yml
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/UserRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/OldStompServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/UserServiceTest.java
Labels: Fix, Refactor, Test
