Repository gnimty/backend-community-service, pull requests merged in 2023-10, with the labels that each got.

#2 feat: WebSocketSessionManager 세션을 통한 연결 감지 및 @EventListener 추가
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/global/auth/WebSocketSessionManager.java
  src/main/java/com/gnimty/communityapiserver/global/config/StompConfiguration.java
  src/main/java/com/gnimty/communityapiserver/global/handler/StompHandler.java
Labels: Feature

#15 Enhance/#7 exist 쿼리 querydsl로 변경
  src/main/java/com/gnimty/communityapiserver/domain/block/repository/BlockQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/block/repository/BlockRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/block/service/BlockReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/repository/ChampionCommentsLikeQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/repository/ChampionCommentsLikeRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/repository/MemberQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/MemberReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/memberlike/repository/MemberLikeQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/memberlike/repository/MemberLikeRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/memberlike/service/MemberLikeReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/oauthinfo/repository/OauthInfoQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/oauthinfo/repository/OauthInfoRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/oauthinfo/service/OauthInfoReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountReadService.java
Labels: Refactor, Enhance

#12 feat: ChatRoom, User CRUD 기능 구현, dto 구현 필요
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/AutoIncrementSequence.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/ChatRoom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/Status.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/User.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryCustom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryCustom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/SeqGeneratorService.java
  src/main/java/com/gnimty/communityapiserver/global/exception/ErrorCode.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/UserRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/SeqGeneratorService.java
Labels: Feature

#13 Feat/#9 챔피언 좋아요/싫어요 삭제
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/repository/ChampionCommentsQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/service/dto/response/ChampionCommentsEntry.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/controller/dto/request/ChampionCommentsLikeRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/repository/ChampionCommentsLikeRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/dto/request/ChampionCommentsLikeServiceRequest.java
  src/main/java/com/gnimty/communityapiserver/global/constant/ResponseMessage.java
  src/main/java/com/gnimty/communityapiserver/global/exception/ErrorCode.java
  src/main/java/com/gnimty/communityapiserver/global/interceptor/TokenAuthInterceptor.java
  src/main/resources/application.yml
Labels: Feature, Fix

#14 채팅 서비스 janguni 파트 구현
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/Chat/ChatRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/dto/ChatDto.java
Labels: Feature

#17 fix: Compile Error resolve
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/repository/ChampionCommentsLikeRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeReadService.java
Labels: Bug

#20 Feat/#16 stomp 사용 시 User 사용
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/Chat/ChatRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/main/java/com/gnimty/communityapiserver/global/auth/JwtProvider.java
  src/main/java/com/gnimty/communityapiserver/global/auth/WebSocketSessionManager.java
  src/main/java/com/gnimty/communityapiserver/global/handler/StompHandler.java
  src/test/resources/application.yml
Labels: Feature

#23 feat/#18 세션 저장 시 User에서 memberId로 변경, 웹소켓 접속혹은 접속 해제 시 사용자 접속상태 변경로직 변경
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/main/java/com/gnimty/communityapiserver/global/auth/JwtProvider.java
  src/main/java/com/gnimty/communityapiserver/global/auth/WebSocketSessionManager.java
  src/main/java/com/gnimty/communityapiserver/global/handler/StompHandler.java
  src/test/resources/application.yml
Labels: Feature

#22 feat: issue#21 내용 반영
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/ChatDto.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/ChatRoomDto.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/ChatRoomInfo.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/UserDto.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryCustom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoom/ChatRoomRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryCustom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/dto/ChatDto.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/dto/ChatRoomSimpleInfoDto.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/dto/UserWithBlockDto.java
  src/main/java/com/gnimty/communityapiserver/global/auth/WebSocketSessionManager.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatServiceTest.java
Labels: Feature

#25 feat/#24 사용자 차단상태, 접속상태 용어 명확화, chatService 마무리
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/Chat.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/ChatRoom.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
Labels: Feature, Refactor

#26 Fix/#4 듀오 추천 시 변경점
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/dto/request/CursorEntry.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/dto/request/RecommendedSummonersRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/dto/request/RecommendedSummonersServiceRequest.java
  src/main/java/com/gnimty/communityapiserver/global/constant/Tier.java
Labels: Feature, Fix

#29 Fix/#4 듀오 추천 시 쿼리 수정
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/repository/ChampionCommentsLikeRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/member/repository/MemberRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/dto/request/CursorEntry.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/dto/request/RecommendedSummonersRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/dto/request/RecommendedSummonersServiceRequest.java
  src/main/java/com/gnimty/communityapiserver/global/constant/Tier.java
  src/main/java/com/gnimty/communityapiserver/global/validation/annotation/ValidateCursor.java
  src/main/java/com/gnimty/communityapiserver/global/validation/validator/SummonerCursorValidator.java
Labels: Bug, Feature, Fix, Refactor

#32 Feat/#28 채팅 서비스 코드 테스트
  src/main/java/com/gnimty/communityapiserver/CommunityapiserverApplication.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/User.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/Chat/ChatRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/repository/UserRepositoryTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatServiceTest.java
Labels: Bug, Test

#35 feat/#33 member,block 서비스와 chat 서비스를 연동, template service로 이동
  src/main/java/com/gnimty/communityapiserver/domain/block/repository/BlockQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/block/service/BlockReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/ChatService.java
Labels: Feature, Refactor
