Repository gnimty/backend-community-service, pull requests merged in 2024-01, with the labels that each got.

#119 Test/#118 챔피언 운용법 관련 테스트
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/controller/ChampionCommentsController.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/controller/dto/request/ChampionCommentsRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/controller/dto/request/ChampionCommentsUpdateRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/entity/ChampionComments.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/repository/ChampionCommentsQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/service/ChampionCommentsReadService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/service/ChampionCommentsService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/service/dto/response/ChampionCommentsEntry.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/controller/ChampionCommentsLikeController.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/controller/dto/request/ChampionCommentsLikeRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/service/ChampionCommentsLikeService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/controller/ChampionCommentsReportController.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/controller/dto/request/ChampionCommentsReportRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/reposiotry/ChampionCommentsReportRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/service/ChampionCommentsReportService.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/service/dto/request/ChampionCommentsReportServiceRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/User.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/global/config/WebClientWrapper.java
  src/main/java/com/gnimty/communityapiserver/global/constant/Bound.java
  src/main/java/com/gnimty/communityapiserver/global/exception/ErrorCode.java
  src/test/java/com/gnimty/communityapiserver/controller/ControllerTestSupport.java
  src/test/java/com/gnimty/communityapiserver/controller/championcomments/ChampionCommentsControllerTest.java
  src/test/java/com/gnimty/communityapiserver/controller/championcommentslike/ChampionCommentsLikeControllerTest.java
  src/test/java/com/gnimty/communityapiserver/controller/championcommentsreport/ChampionCommentsReportControllerTest.java
  src/test/java/com/gnimty/communityapiserver/controller/member/MemberControllerTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/UserServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/block/BlockReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcomments/ChampionCommentsReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcomments/ChampionCommentsServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcommentslike/ChampionCommentsLikeReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcommentslike/ChampionCommentsLikeServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcommentsreport/ChampionCommentsReportServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/member/MemberServiceTest.java
Labels: Feature, Fix, Refactor, Test

#121 Test/#120 내 정보 관련 테스트
  src/main/java/com/gnimty/communityapiserver/domain/memberlike/controller/dto/request/MemberLikeRequest.java
  src/test/java/com/gnimty/communityapiserver/controller/ControllerTestSupport.java
  src/test/java/com/gnimty/communityapiserver/controller/memberlike/MemberLikeControllerTest.java
  src/test/java/com/gnimty/communityapiserver/service/introduction/IntroductionReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/memberlike/MemberLikeReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/memberlike/MemberLikeServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/oauthinfo/OauthInfoReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/prefergamemode/PreferGameModeReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/schedule/ScheduleReadServiceTest.java
Labels: Fix, Test

#122 fix: redis image version 변경
  docker-compose-dev.yml
Labels: Fix

#127 Bug/#126 bug fix chat service
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/global/handler/StompHandler.java
Labels: Bug

#130 chore: websocket관련 로그 추가
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/global/connect/WebSocketSessionManager.java
Labels: Chore

#128 fix: token check path 수정
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/MemberController.java
  src/main/java/com/gnimty/communityapiserver/global/config/WebConfiguration.java
  src/main/java/com/gnimty/communityapiserver/global/interceptor/TokenAuthInterceptor.java
Labels: Bug

#136 Bug/#135 웹소켓 연결, 연결해제 시 상태값 변경 버그 수정
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/member/service/MemberService.java
  src/main/java/com/gnimty/communityapiserver/global/handler/StompHandler.java
  src/main/java/com/gnimty/communityapiserver/global/interceptor/TokenAuthInterceptor.java
Labels: Bug

#139 Feat: 웹소켓 연결 시 사용자가 선택한 상태값으로 변경
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/ChatController.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/controller/dto/UserDto.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/entity/User.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryImpl.java
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/MemberController.java
  src/test/java/com/gnimty/communityapiserver/controller/member/MemberControllerTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatRoomServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/UserServiceTest.java
Labels: Feature

#138 Test/#132 riot account test
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/SummonerUpdateEntry.java
  src/main/java/com/gnimty/communityapiserver/domain/member/controller/dto/request/SummonerUpdateRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/controller/dto/request/RecommendedSummonersRequest.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/repository/RiotAccountQueryRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/service/RiotAccountService.java
  src/main/java/com/gnimty/communityapiserver/global/constant/ApiDescription.java
  src/main/java/com/gnimty/communityapiserver/global/constant/RequestPattern.java
  src/test/java/com/gnimty/communityapiserver/controller/ControllerTestSupport.java
  src/test/java/com/gnimty/communityapiserver/controller/riotaccount/RiotAccountControllerTest.java
  src/test/java/com/gnimty/communityapiserver/service/ServiceTestSupport.java
  src/test/java/com/gnimty/communityapiserver/service/block/BlockReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/block/BlockServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcomments/ChampionCommentsReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcomments/ChampionCommentsServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcommentslike/ChampionCommentsLikeReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcommentslike/ChampionCommentsLikeServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/championcommentsreport/ChampionCommentsReportServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/introduction/IntroductionReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/member/AuthServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/member/MemberServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/memberlike/MemberLikeReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/memberlike/MemberLikeServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/oauthinfo/OauthInfoReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/prefergamemode/PreferGameModeReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/riotaccount/RiotAccountReadServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/riotaccount/RiotAccountServiceTest.java
  src/test/java/com/gnimty/communityapiserver/service/schedule/ScheduleReadServiceTest.java
Labels: Fix, Test

#144 Bug/#143 update conn status bug
  src/main/java/com/gnimty/communityapiserver/domain/chat/service/StompService.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/UserServiceTest.java
Labels: Bug, Test

#147 Release/#131 embedded mongodb
  build.gradle
  src/main/java/com/gnimty/communityapiserver/domain/chat/repository/User/UserRepositoryImpl.java
  src/main/resources/application.yml
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatRoomServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/ChatServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/StompServiceTest.java
  src/test/java/com/gnimty/communityapiserver/domain/chat/service/UserServiceTest.java
Labels: Chore, Fix, Release

#146 enhance: 조회 쿼리문 index 적용
  src/main/java/com/gnimty/communityapiserver/domain/block/entity/Block.java
  src/main/java/com/gnimty/communityapiserver/domain/championcomments/entity/ChampionComments.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentslike/entity/ChampionCommentsLike.java
  src/main/java/com/gnimty/communityapiserver/domain/championcommentsreport/entity/ChampionCommentsReport.java
  src/main/java/com/gnimty/communityapiserver/domain/introduction/entity/Introduction.java
  src/main/java/com/gnimty/communityapiserver/domain/member/entity/Member.java
  src/main/java/com/gnimty/communityapiserver/domain/memberlike/entity/MemberLike.java
  src/main/java/com/gnimty/communityapiserver/domain/memberlike/repository/MemberLikeRepository.java
  src/main/java/com/gnimty/communityapiserver/domain/oauthinfo/entity/OauthInfo.java
  src/main/java/com/gnimty/communityapiserver/domain/riotaccount/entity/RiotAccount.java
  src/main/resources/application.yml
Labels: Enhance
